spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
telegram:
  bot:
    name: ${TG_NAME}
    token: ${TG_TOKEN}
selenium:
  url: ${SELENIUM_URL}
  proxyip: ${SELENIUM_PROXYIP}
